name: shaple_flutter
description: Flutter integration for Shaple.
version: 0.2.0
homepage: 'https://github.com/paust-team/shaple-flutter'
repository: 'https://github.com/paust-team/shaple-flutter/tree/main/packages/shaple_flutter'
documentation: 'https://github.com/paust-team/shaple-flutter'

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shaple: ^0.1.3
  app_links: ^3.5.0
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  async: ^2.11.0
  http: '>=0.13.5 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  dart_jsonwebtoken: ^2.13.0
  path: ^1.8.3

platforms:
  android:
  ios:
  macos:
  web:
  windows:

flutter:
