name: shaple
description: A dart client for Shaple.
version: 0.1.1
homepage: 'https://github.com/paust-team/shaple-flutter'
repository: 'https://github.com/paust-team/shaple-flutter/tree/main/packages/shaple'
documentation: 'https://github.com/paust-team/shaple-flutter'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  gotrue: ^2.3.0
  http: '>=0.13.5 <2.0.0'

dev_dependencies:
  lints: ^2.1.1
  test: ^1.17.9
  web_socket_channel: ^2.2.0
